---

- include_vars: secrets.yml
  no_log: False

- debug: msg="API call out"


- name: host checklist post for RDBMS install
  include_tasks: host_checklist_post_update.yml
  vars:
    chklst_json_body:
      new_entry: True
      host_name: "{{ ansible_hostname }}"
      checklist_type: "RDBMS Software Install"
      checklist_category: Install
      db_install_status: STARTED
      task_desc: RDBMS INSTALL
  tags:
  - apex_api

- include: determine_db_home.yml
  when:
  - oracle_db_home is not defined
  - inventory_hostname == master_node

- name: copy oracle_db_home fact to other nodes
  set_fact:
    oracle_db_home: "{{ hostvars[master_node]['oracle_db_home'] }}"
  when: inventory_hostname != master_node

- include: copy_archives.yml

- name: create cluster_node_string
  set_fact:
    cluster_node_string: "{{ cluster_node_string | default([]) }} + [ '{{ hostvars[node_name]['ansible_hostname'] }}' ]"
  loop: "{{ cluster_nodes }}"
  loop_control:
    loop_var: node_name

- include: prep_rsp_file.yml
  when: inventory_hostname == master_node

- include: oracle.yml
